apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
spec:
  project: default
  source:
    repoURL: https://github.com/jdemend/hello-world.git
    targetRevision: {{ targetRevision }}
    path: bundles/saas/helm/org-api
  destination:
    server: https://kubernetes.default.svc
    namespace: org-public
  syncPolicy:
     automated: {}
