apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: org-api
spec:
  project: default
  source:
    repoURL: https://github.com/jamesphillpotts-fr/helm-hello-world.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
     automated: {}
