apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: org-api
spec:
  project: default
  source:
    repoURL: https://github.com/jdemend/hello-world.git
    targetRevision: test1
    path: bundles/saas/helm/hello-world1
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
     automated: {}
