apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world1
  namespace: default
  labels:
    app: hello-world1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world1
  template:
    metadata:
      labels:
        app: hello-world1
    spec:
      containers:
        - name: hello-world1
          image: gcr.io/hello-minikube-zero-install/hello-node
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          # initialDelaySeconds for initializeOrganization in main.go to complete
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /
              port: http
