apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jdemend/hello-world.git
    targetRevision: test1
    path: bundles/saas/helm/hello-world2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
     automated: {}
